name: Repo Dispatcher
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select code branch to build'
        default: 'master'
        required: true
      device:
        description: 'select device to build'
        default: 'r2s'
        required: true
      debug:
        type: choice
        description: 'debug?'
        options:
        - true
        - false
        default: 'false'
        required: true
      cache_save:
        type: choice
        description: 'check to save cache'
        options:
        - true
        - false
        default: 'true'
        required: true
      package_clean:
        type: choice
        description: 'check to make clean package'
        options:
        - true
        - false
        default: 'false'
        required: true
      runner:
        type: choice
        description: Where to run
        options:
        - ubuntu-latest
        - self-hosted
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.SEC_TOKEN }}" \
            -d '{"event_type": "${{ github.event.inputs.device }}", "client_payload": {"branch": "${{ github.event.inputs.branch }}", "device": "${{ github.event.inputs.device }}", "debug": "${{ github.event.inputs.debug }}", "cache_save": "${{ github.event.inputs.cache_save }}", "package_clean": "${{ github.event.inputs.package_clean }}", "runner": "${{ github.event.inputs.runner }}"}}'
