name: Repo Dispatcher
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r2s'
        required: false
      debug:
        description: 'debug?'
        default: 'true'
        required: true
      cache_save:
        description: 'check to save cache'
        default: 'false'
        required: true
      package_clean:
        description: 'check to make clean package'
        default: 'false'
        required: true
      runner:
        description: 'runner to run'
        default: 'ubuntu-18.04'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.SEC_TOKEN }}" \
            -d '{"event_type": "${{ github.event.inputs.device }}", "client_payload": {"device": "${{ github.event.inputs.device }}", "debug": "${{ github.event.inputs.debug }}", "cache_save": "${{ github.event.inputs.cache_save }}", "package_clean": "${{ github.event.inputs.package_clean }}", "runner": "${{ github.event.inputs.runner }}"}}' \
            -v
